package uk.ac.warwick.cs126.structures;

public class Entry<K,V>{
    public K key;
    public V value;

    public Entry(K k, V v){
        key=k;
        value=v;
    }

    public K getKey() {
        return key;
    }

    public V getValue() {
        return value;
    }

    public Entry() {

    }

    //Following code were generated by Jetbrains IDEA equals and hashcode template.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Entry<?, ?> entry = (Entry<?, ?>) o;
        if (key != null ? !key.equals(entry.key) : entry.key != null) return false;
        return value != null ? value.equals(entry.value) : entry.value == null;
    }

    @Override
    public int hashCode() {
        int result = key != null ? key.hashCode() : 0;
        result = 31 * result + (value != null ? value.hashCode() : 0);
        return result;
    }
}
